/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AudioDownloadQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OnMediaConvertComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OnTranscribeComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "RssRefreshQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TranscriptIngestQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}