/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnalyzeAudio": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AudioAnalysisDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AudioAnalysisQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AudioDownloadDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AudioDownloadQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AudioTranscodeDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AudioTranscodeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BuildTasteProfiles": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CheckStaleTranscriptions": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiscoverEpisodes": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiscoveryDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DiscoveryQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DownloadAudio": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DownloadImage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FetchRss": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateHlsSubtitles": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ImageDownloadDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageDownloadQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageProcessingDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageProcessingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IngestListeningEvents": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListeningEventsDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ListeningEventsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OnMediaConvertComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OnTranscribeComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OnTranscriptionWebhook": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ProcessImage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessTranscript": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessingDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProcessingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ResizeImage": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "RollupListening": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RssRefreshDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "RssRefreshQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StartProcessing": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SubtitleGenerationDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SubtitleGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TranscodeAudio": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TranscriptIngestDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TranscriptIngestQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}