import { rssParser } from '../shared/rss-parser';
import {
  getItunesImageHref,
  pickBestImageUrl,
  extractOwner,
} from '../fetch-rss/handler';

export interface FeedValidationResult {
  valid: boolean;
  reasons: string[];
  imageUrl: string | null;
  ownerEmail: string | null;
}

/**
 * Patterns that strongly indicate AI/TTS-generated podcast content.
 * Matched case-insensitively against title, author, and description.
 */
const AI_TITLE_PATTERNS = [
  /\bai[- ]generated\b/i,
  /\bai[- ]powered podcast\b/i,
  /\bautomated daily\b/i,
  /\bgenerated by ai\b/i,
  /\bfully automated\b/i,
  /\brobot[- ]narrated\b/i,
  /\bai narrat(?:ed|or|ion)\b/i,
  /\btext[- ]to[- ]speech\b/i,
];

const AI_DESCRIPTION_PATTERNS = [
  /powered by (?:cutting[- ]edge )?generative ai/i,
  /generated (?:entirely )?(?:using|by|with) (?:artificial intelligence|ai|large language|llm|gpt|openai|elevenlabs|google tts|amazon polly)/i,
  /ai[- ]generated (?:podcast|audio|episode|content|narration|voice)/i,
  /no human host/i,
  /entirely ai[- ](?:produced|created|generated)/i,
  /automated (?:podcast|news|audio) (?:production|generation|creation)/i,
];

function looksAiGenerated(
  title: string,
  author: string,
  description: string,
): string | null {
  for (const pat of AI_TITLE_PATTERNS) {
    if (pat.test(title)) return `title matches "${pat.source}"`;
  }
  for (const pat of AI_TITLE_PATTERNS) {
    if (pat.test(author)) return `author matches "${pat.source}"`;
  }
  for (const pat of AI_DESCRIPTION_PATTERNS) {
    if (pat.test(description)) return `description matches "${pat.source}"`;
  }
  return null;
}

/**
 * Validate an RSS feed for ingestion quality. Returns detailed results
 * so the caller can log reasons for rejection.
 *
 * Checks:
 * 1. Feed has an image URL that resolves (HTTP 200, non-empty body)
 * 2. Feed has an itunes:owner email address
 * 3. Feed does not appear to be AI-generated
 */
export async function validateFeed(rssUrl: string): Promise<FeedValidationResult> {
  const reasons: string[] = [];

  let feed: Awaited<ReturnType<typeof rssParser.parseURL>>;
  try {
    feed = await rssParser.parseURL(rssUrl);
  } catch (err) {
    return { valid: false, reasons: [`Failed to parse RSS: ${err}`], imageUrl: null, ownerEmail: null };
  }

  const imageUrl = pickBestImageUrl(feed.itunesImage, feed.image?.url) ?? null;
  const owner = extractOwner(feed.itunesOwner);
  const ownerEmail = owner.email ?? null;

  // 1. Image must exist and be reachable
  if (!imageUrl) {
    reasons.push('No image URL in feed (missing itunes:image and rss image)');
  } else {
    try {
      const res = await fetch(imageUrl, {
        method: 'HEAD',
        redirect: 'follow',
        signal: AbortSignal.timeout(8000),
      });
      if (!res.ok) {
        reasons.push(`Image URL returned HTTP ${res.status}: ${imageUrl}`);
      } else {
        const contentLength = res.headers.get('content-length');
        if (contentLength === '0') {
          reasons.push(`Image URL returned empty body: ${imageUrl}`);
        }
      }
    } catch (err) {
      reasons.push(`Image URL unreachable: ${imageUrl} (${err})`);
    }
  }

  // 2. Owner email is required
  if (!ownerEmail) {
    reasons.push('No itunes:owner email in feed');
  }

  // 3. AI-generated content check
  const title = feed.title ?? '';
  const author = (feed.itunesAuthor as string) ?? '';
  const description = feed.description ?? (feed.itunesSummary as string) ?? '';
  const aiReason = looksAiGenerated(title, author, description);
  if (aiReason) {
    reasons.push(`Appears AI-generated: ${aiReason}`);
  }

  return {
    valid: reasons.length === 0,
    reasons,
    imageUrl,
    ownerEmail,
  };
}
